version: '2'
services:
  php:
    container_name: "${PROJECT_NAME}php"
    image: petronetto/php-nginx:laravel
    volumes:
     - ./application:/var/www/app
    links:
     - database
     - redis
    ports:
     - "80:${HTTP_PORT}"
     - "443:${HTTPS_PORT}"
  database:
    container_name: "${PROJECT_NAME}database"
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
     - ./data:/var/lib/mysql
    ports:
     - "3306:${MYSQL_PORT}"
  redis:
    container_name: "${PROJECT_NAME}redis"
    image: redis:alpine
volumes:
  data:
    driver: "local"
