# I use ENV variables to name my containers and set the ports
# to change, replate it here or in .env file
version: '2'
services:
  php:
    container_name: ${APP_NAME}-php
    # Image with Alpine instead Ubuntu
    # image: petronetto/php-nginx-alpine
    image: petronetto/php-nginx
    restart: always
    volumes:
     - ./src:/var/www/src
    links:
     - database
     - redis
    ports:
     - ${HTTP_PORT}:80
     - ${HTTPS_PORT}:443
  database:
    container_name: ${APP_NAME}-database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_USER: ${MYSQL_USER} 
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # Limit buffer size to avoid MySQL consume all memory in low-cost servers
    command: mysqld --innodb-buffer-pool-size=64M
    volumes:
     - ./data:/var/lib/mysql
    ports:
     - ${MYSQL_PORT}:3306
  redis:
    container_name: ${APP_NAME}-redis
    image: redis:alpine
    restart: always
  debug:
    container_name: ${APP_NAME}-debug
    image: petronetto/php-debug
    restart: always
    environment:
      XDEBUG_HOST: ${DEBUG_HOST}
    volumes:
      - ./src:/var/www/html
    ports:
      - ${DEBUG_PORT}:80
    links:
     - database
     - redis
volumes:
  data:
    driver: local
